"""Initial migration for Mapgenius Solutions.

Creates core tables: users, invoices, financial_data.
All tables include appropriate primary keys, foreign keys, and
basic constraints suitable for a financial SaaS platform.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("email", sa.String(length=255), nullable=False, unique=True),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now()),
    )

    op.create_table(
        "invoices",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("status", sa.Enum("draft", "issued", "paid", "canceled", name="invoice_status"), nullable=False, server_default="draft"),
        sa.Column("total_amount_cents", sa.BigInteger, nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="USD"),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now()),
    )

    op.create_table(
        "financial_data",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("invoice_id", sa.BigInteger, sa.ForeignKey("invoices.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rfc", sa.String(length=13), nullable=False),
        sa.Column("amount_cents", sa.BigInteger, nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Add indexes that will be useful for financial reporting.
    op.create_index("ix_invoices_user_id", "invoices", ["user_id"])
    op.create_index("ix_invoices_status", "invoices", ["status"])
    op.create_index("ix_financial_data_invoice_id", "financial_data", ["invoice_id"])
    op.create_index("ix_financial_data_rfc", "financial_data", ["rfc"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.drop_index("ix_financial_data_rfc", table_name="financial_data")
    op.drop_index("ix_financial_data_invoice_id", table_name="financial_data")
    op.drop_index("ix_invoices_status", table_name="invoices")
    op.drop_index("ix_invoices_user_id", table_name="invoices")
    op.drop_table("financial_data")
    op.drop_table("invoices")
    op.drop_table("users")
    # ### end Alembic commands ###
